### ISSUE TITLE
Please find an additional maintainer for this project

### ISSUE THREAD

**Issue by damianh** [fclp/fluent-command-line-parser#101]
It's a nice lib and it's a shame that it is dying. 

Alternatively, can someone point to a maintained fork, if such exists? TY.

**Comment by siywilliams** [comment]
I don't consider it "dying" myself, however we all view things differently.

What kind of features and development are you hoping for in this library?

**Comment by jzabroski** [comment]
I think he is referring to the fact 1.5 has been in pre-release on NuGet for 9 months.

**Comment by damianh** [comment]
@jzabroski is pretty much correct. When people ship forks [1](https://www.nuget.org/packages/FluentCommandLineParser-netstandard/), [2](https://www.nuget.org/packages/FluentCommandLineParserDotnetCore/) (without changes too) it's usually a smell. NetStandard and NetCore been out for years (I'd agree that 2.0 is the "mainstream" release) and this project isn't any closer to shipping a supporting package. I'm sure there is someone willing to help you for when you aren't able to work on it. 

Also shipping netstandard support as an entirely [separate nuget](https://www.nuget.org/packages/FluentCommandLineParser.NETStandard/1.5.0.31-commands) is not standard procedure.

Cheers

**Comment by jzabroski** [comment]
This project had some promise.  Crazy how much time has flown by.  In any event I stopped using this tool because of a dangerous parsing behavior that would cause 'shadowed prefixes' to get eagerly consumed and result in unexpected results for the end-user.

**Comment by EricZimmerman** [comment]
I switched the Microsoft system commandline package for everything. Works great once you get the basics down.

**Comment by damianh** [comment]
Yeah there are better options out there now e.g. Spectre.Cli
