### ISSUE TITLE
Question: Use a string from another source to populate arguments?

### ISSUE THREAD

**Issue by EricZimmerman** [fclp/fluent-command-line-parser#107]
is it possible to start with a string of command line args, say, in a separate file, and, if that file exists, read it, and update args with said commandline?

In other words, id like to provide a way for fluent to read a command line and parse it into the argument object i have. 

if its not possible for this project to take a string and cut it up, is there a method any knows of that allows me to essentially pass in such a string and end up with a string array, just like args ends up looking like when a program starts?

thanks!

**Comment by siywilliams** [comment]
There is no current overload for just a string so you'll have to provide your own extension to convert a `string` into `string[]`.

I don't have a good implementation to share sadly, and after a quick google it appears no one else has a particulary great method of doing so either unfortunately.

If there is a solution that I could integrate into the library that would be super for a lot of people.

**Comment by EricZimmerman** [comment]
thanks! ill see what i can do
