### ISSUE TITLE
Get Help text apart from SetupHelp callback

### ISSUE THREAD

**Issue by MuiBienCarlota** [fclp/fluent-command-line-parser#29]
I need a way to get help text (same text as sent to Callback) but appart from Callback.

I some case, help is not asked by caller but some parameters failed a second stage validation (something like "Is the file designated by the parameter exists") and I want to Print error message followed by standard usage.

**Comment by siywilliams** [comment]
It's not ideal but you can get the help text outside of the callback.

```c#
var p = new Fclp.FluentCommandLineParser();

string helpText;

// setup help as normal
p.SetupHelp("?")
  .Callback(s => helpText = s);
            
// manually call show help, this will trigger the callback setup in SetupHelp
p.HelpOption.ShowHelp(parser.Options);
```

Beware that if you call ```p.HelpOption.ShowHelp``` before ```p.SetupHelp``` it will throw a ```NotSupportedException```

**Comment by MuiBienCarlota** [comment]
I'm using nuget version (FluentCommandLineParser.1.4.0) and generic version:

    var p = new FluentCommandLineParser<PushJob>();
    p.SetupHelp("h", "help", "?").Callback(s => Console.WriteLine(s));

I don't have any HelpOption available (neither public nor private). I can cast Parser property:

    FluentCommandLineParser innerParser = p.Parser as FluentCommandLineParser;

but HelpOption is protected and its implementation is internal (Fclp.Internals.HelpCommandLineOption) so reflexion can be cumbersome.

Do you think it can be integrated into a futur version?

**Comment by siywilliams** [comment]
Ah yes my mistake, you're using the generic parser ```FluentCommandLineParser<T>``` which doesn't have that property.

Another temperary alternative is to use the formatter directly

```c#
var p = new FluentCommandLineParser<PushJob>();

var helpText = new CommandLineOptionFormatter().Format(p.Parser.Options);
```

I'll look into adding something more acceptable.

**Comment by MuiBienCarlota** [comment]
Great solution. I found it very acceptable but you may prefer to limit helper class visibility to advanced scenarios  (I wasn't aware of CommandLineOptionFormatter).

**Comment by siywilliams** [comment]
From v1.4.1 you can now do the following to manually execute the SetupHelp callback.

```c#
var p = new FluentCommandLineParser<Args>(); // or non generic: new FluentCommandLineParser(); 

string helpText;

p.SetupHelp("?")
  .Callback(s => helpText = s);
            
p.HelpOption.ShowHelp(parser.Options);
```

**Comment by MuiBienCarlota** [comment]
Great. Thanks!
