### ISSUE TITLE
Boolean parser doesn't parse single dash with full option name and no argument/suffix

### ISSUE THREAD

**Issue by ian-moore** [fclp/fluent-command-line-parser#33]
Truthfully not sure if this is a bug or not, but the README indicates that [/|--|-] should be equivalent. If I have a boolean option, I can do 

````
--myoption
-m
/myoption
/m
```

but not

    -myoption

And instead get a [pretty crummy exception](https://github.com/fclp/fluent-command-line-parser/blob/develop/FluentCommandLineParser/Internals/CommandLineOption.cs#L155)


If it's not a bug, I think the README should be updated to reflect this behavior - and return it as an error or something in the parse result rather than throw an exception.

**Comment by siywilliams** [comment]
Thanks @ian-moore 

Not really a bug, just the way the options are interpreted. It was also highlighted in issue https://github.com/fclp/fluent-command-line-parser/issues/24

A single dash denotes a short option, and grouped short option are supported, so the parser is interpreting `-myoption` as `-m -y -o -p -t -i -o -n` options.

That being said, I agree with you regarding the README and error thrown. That section of the readme wasn't updated correctly after the short option grouping was added.

**Comment by ian-moore** [comment]
Sorry, didn't catch that in the readme about the multiple short options. Thanks for pointing out - cool feature. Would be nice if that was near the rest of syntax explanation. After pulling down the source and testing this out, I can't reproduce and I see the exception caught in the location you linked to. Not sure why it lets the exception escape in the project I added the latest nuget package too... I'll keep looking.

**Comment by siywilliams** [comment]
I'll try and get round to improving the readme, I might also include a way of optionally disabling combined options, which would allow `-myoption` to resolve to a long option name.

Did you have 'break when an exception is thrown' enabled for CLR Exceptions in Visual Studio? That would cause the debugger to break when it was thrown. Other than that I can't think of any other reason.
