### ISSUE TITLE
Please add support for Nullable<DateTime>

### ISSUE THREAD

**Issue by DashNY** [fclp/fluent-command-line-parser#36]
I get an error on Nullable<DateTime> property. It would be great if the parser could support it

**Comment by siywilliams** [comment]
@DashNY Before I release to nuget, can you try out the [latest build](http://teamcity.codebetter.com/viewLog.html?buildId=191670&tab=artifacts&buildTypeId=bt951)?

**Comment by DashNY** [comment]
@siywilliams Appears to be working as expected. Please release as nuget.

**Comment by siywilliams** [comment]
https://www.nuget.org/packages/FluentCommandLineParser/1.4.2
