### ISSUE TITLE
Support long/int64

### ISSUE THREAD

**Issue by kakashif** [fclp/fluent-command-line-parser#40]
There is no support for long types.  There are cases where there is a need to parse something longer than int.max.

**Comment by kakashif** [comment]
I had already started working on it after coping the repo.  I was advised by a fellow worker to create an issue and submit and PR.  So hopefully this will be accepted and will be my first submission to an open source project.

**Comment by siywilliams** [comment]
Thanks @kakashif can you open a pull request with your code changes?

**Comment by kakashif** [comment]
Will do. I am updating some test cases before I create the PR.

**Comment by kakashif** [comment]
PR submitted: https://github.com/fclp/fluent-command-line-parser/pull/41
I do not know the policy for adding licensing information.  If you have something specific you want added, please let me know and I will update the PR.

**Comment by siywilliams** [comment]
Now available through [v1.4.3 Nuget package](https://www.nuget.org/packages/FluentCommandLineParser/1.4.3)
