### ISSUE TITLE
Nullable enum support

### ISSUE THREAD

**Issue by KvanTTT** [fclp/fluent-command-line-parser#43]
Current version does not support nullable enum. It will be good to support it.

**Comment by siywilliams** [comment]
Good idea, I've implemented it and will release to nuget soon.

**Comment by siywilliams** [comment]
Now available through [v1.4.3 Nuget package](https://www.nuget.org/packages/FluentCommandLineParser/1.4.3)

**Comment by KvanTTT** [comment]
Thank you so much!
