### ISSUE TITLE
Need strong named assembly

### ISSUE THREAD

**Issue by cakriwut** [fclp/fluent-command-line-parser#46]
Please sign the assembly in Nuget package so that we can use the strong named assembly. 
Thanks.

**Comment by siywilliams** [comment]
I've actually never signed an assembly before; I've started this process a few times but I've always ran into problems along the way - that's why there is a strongly named key in the solution, but no signed assembly yet :(

**Comment by cakriwut** [comment]
Thanks, I can see the snk in the solution. 
I also have problem with signed assembly if consumer is signed while one or more references are not signed.

**Comment by phillashworth** [comment]
Just a 'me too', I also I can't use FluentCommandLineParser in my project as it doesn't have a strong name.

**Comment by martincostello** [comment]
+1

**Comment by siywilliams** [comment]
I've setup the build system to create a signed version of the dll. You can try this out with the develop build [here](http://github.com).

No signed nuget or release version yet though, I'm just confirming that the develop signed is OK first

**Comment by MuiBienCarlota** [comment]
For this kind of needs, I use [.NET Assembly Strong-Name Signer](https://github.com/brutaldev/StrongNameSigner). It's very easy to use.

**Comment by vstam42** [comment]
I need a strong name as well. If you are interested I can make it and then create pull request.

**Comment by siywilliams** [comment]
I thought I already had one building at teamcity.codebetter.com but I've just realised that it has since been migrated to teamcity.jetbrains.com and everything is now broke.

**Comment by vstam42** [comment]
So do you want me to create it as well as nuget package so it is easier to handle it. Something like
FluentCommandLineParser-StronglyNamed

**Comment by siywilliams** [comment]
FluentCommandLineParser.Signed now available (for v1.5 onwards) on [nuget](https://www.nuget.org/packages/FluentCommandLineParser.Signed)
