### ISSUE TITLE
Support 0 and 1 for bool false and true

### ISSUE THREAD

**Issue by TheCycoONE** [fclp/fluent-command-line-parser#56]
There are currently a few ways of specifying boolean arguments, but I would one more. I think it is reasonable to be able to pass 0 for false and 1 for true. Powershell commands normally support 0 or 1 anywhere they would accept $false / $true (which are currently supported).

**Comment by siywilliams** [comment]
Yes you're quite right, it currently supports true/false on/off and +/- but not 1/0

It's a simple mod so I'll update it.
