### ISSUE TITLE
No side-by-side syntax comparison between other command line parsers

### ISSUE THREAD

**Issue by alekdavis** [fclp/fluent-command-line-parser#62]
The link for _side-by-side syntax comparison between other command line parsers_ at http://fclp.github.io/fluent-command-line-parser/ point to an template page with no useful information. I'm not sure if the URL is wrong or if the page does not exist at all.

**Comment by v-karbovnichiy-parc** [comment]
+1

**Comment by siywilliams** [comment]
The comparison went a bit crazy, I suspect the way I put it together wasn't the best and in the end I decided to remove it as it would cause more problems than it tried to solve.

My main motivation for this library was to get rid of attributes, so it was to mainly show that off. 

In any case I've got no intention of putting the information together again, I think the library stands up on its own now anyway.

Thanks for highlighting it.
