### ISSUE TITLE
Object produced by generic FluentCommandLineParser contains default values, instead of parsed values  when initialized with a struct

### ISSUE THREAD

**Issue by kylos101** [fclp/fluent-command-line-parser#67]
Greetings! 

Thank you very much for providing this library! I recently downloaded it from Nuget, and was able to get it working with the non-generic parser. Very straight forward - your documentation on github was helpful.

I had some trouble with the generic Fluent Command Line Parser, though - the object the parser creates did not contain the parsed values, instead its values were initialized with default values (strings and enums were null, bools were false, etc.). 

I was doing this:
var parser = new FluentCommandLineParser<ApplicationArguments>();
When ApplicationArguments is a struct, parser.Object does not contain the parsed values (as described above).

When ApplicationArguments is a class, parser.Object contains parsed values. I'm not sure why structs don't work yet, but wanted to give you a heads up. 

I'm guessing something like this may help restrict users to only using class arg containers (in FluentCommandLineParserT.cs)?
public class FluentCommandLineParser<TBuildType> : IFluentCommandLineParser<TBuildType> where TBuildType : class, new()

Also, as an FYI, I'm not getting errors, empty args, help, unmatched options, or additional options found. Let me know if you need any other detail - take care.

**Comment by siywilliams** [comment]
Thanks for the feedback @kylos101 

Yes I think it should be changed to class types only, as the mechanism to set the values clearly doesn't work with structs. A person with a good eye such as yourself can work out whats wrong but some people might get turned off by the library if they encounter this issue at first.
