### ISSUE TITLE
Alternatives?

### ISSUE THREAD

**Issue by DixonDs** [fclp/fluent-command-line-parser#81]
The project seems to be dead now, so does anybody know any good alternatives?

**Comment by pyrocumulus** [comment]
@DixonDs 
Perhaps one of the following:

- https://github.com/nemec/clipr
- https://github.com/jpdillingham/Utility.CommandLine.Arguments (pretty new still)

**Comment by DixonDs** [comment]
@pyrocumulus Thanks, I've ended up using https://github.com/gsscoder/commandline

**Comment by pyrocumulus** [comment]
@DixonDs Wow that one is pretty old and still actively maintained. Nice.
